package processing.test.sketch_231025b;

/* autogenerated by Processing revision 1293 on 2023-10-25 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import netP5.*;
import oscP5.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_231025b extends PApplet {




OscP5 oscP5;
NetAddress myRemoteLocation;

String t;

public void setup(){
  /* size commented out by preprocessor */;
  rectMode( CENTER );
  
  oscP5 = new OscP5(this,12000);
  
  myRemoteLocation = new NetAddress("192.168.0.209",12000);
  t = "esta es la variable";
}

public void draw(){
  //boton1
  rect( width/2, height/60, 200,200);
}

public void mousePressed(){
  if( mouseX>width/2-100 && mouseX < width/2+100 & mouseY > height/60-100 && mouseY < height/60+100 ){
    OscMessage myMessage = new OscMessage("/test");
    
    myMessage.add( "este es el msj"  ); /* add a string to the osc message */
    println( "hola" );
    /* envia el mensaje */
    oscP5.send(myMessage, myRemoteLocation); 
      }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_231025b" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
